#Turtle Graphic Project
#2/18/2020
#CTI-110 P2HW2 - Turtle Graphic
#Jerry Cole
import turtle
turtle.forward(100)
turtle.clear()
turtle.penup()
turtle.right(180)
turtle.forward(300)
turtle.right(135)
turtle.pendown()
turtle.fillcolor('green')
turtle.begin_fill()
turtle.forward (100)
turtle.right (90)
turtle.forward (100)
turtle.right (90)
turtle.forward (100)
turtle.right (90)
turtle.forward (100)
turtle.end_fill()
turtle.penup()
turtle.right (135)
turtle.forward (140)
turtle.right (45)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
turtle.forward (100)
turtle.left (90)
turtle.forward (100)
turtle.left (90)
turtle.forward (100)
turtle.left (90)
turtle.forward (100)
turtle.end_fill()
            
